title: MVPArms
description: a common Architecture for Android Applications developing based on MVP，integrates many Open Source Projects ,to make your developing quicker and easier. ( 一个整合了大量主流开源项目的 Android MVP 快速搭建框架)
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
